# -*- coding: utf-8 -*-
"""datawh_As4_67160220.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqN_LxYKWucQ_FGLJnR8qRKqrGVioWVm
"""

import sqlite3
import pandas as pd
from pathlib import Path

DATA_PATH = "retail_logs.csv"
DB_PATH = "retail_warehouse.db"

def extract() -> pd.DataFrame:
    """Extract: อ่านข้อมูลดิบจากไฟล์ CSV"""
    try:
        df = pd.read_csv(DATA_PATH)
        # ปรับชื่อคอลัมน์ให้เป็นตัวพิมพ์เล็กและตัดช่องว่างออกให้จัดการง่าย
        df.columns = [c.strip().lower() for c in df.columns]
        print(f"[Extract] Loaded {len(df):,} rows from {DATA_PATH}")
        return df
    except FileNotFoundError:
        raise FileNotFoundError(f"ไม่พบไฟล์ {DATA_PATH} กรุณาตรวจสอบว่ามีไฟล์นี้อยู่ในโฟลเดอร์เดียวกับสคริปต์")

def transform(df: pd.DataFrame):
    """Transform: แปลงข้อมูลให้อยู่ในรูปแบบ Star Schema"""

    col_date = 'date' if 'date' in df.columns else 'timestamp' if 'timestamp' in df.columns else df.columns[0]
    col_location = 'branch' if 'branch' in df.columns else 'location'
    col_product = 'product' if 'product' in df.columns else 'product_name'
    col_qty = 'quantity' if 'quantity' in df.columns else 'qty'
    col_price = 'price' if 'price' in df.columns else 'unit_price'
    col_tx = 'transaction_id' if 'transaction_id' in df.columns else 'order_id'

    if col_qty not in df.columns: df[col_qty] = 1
    if col_price not in df.columns: df[col_price] = 0.0

    df[col_date] = pd.to_datetime(df[col_date], errors="coerce")
    df = df.dropna(subset=[col_date]).copy()

    dim_date = df[[col_date]].drop_duplicates().sort_values(col_date).reset_index(drop=True)
    dim_date = dim_date.rename(columns={col_date: "full_date"})
    dim_date["date_id"] = dim_date["full_date"].dt.strftime("%Y%m%d").astype(int)
    dim_date["day"] = dim_date["full_date"].dt.day
    dim_date["month"] = dim_date["full_date"].dt.month
    dim_date["year"] = dim_date["full_date"].dt.year
    dim_date = dim_date[["date_id", "full_date", "day", "month", "year"]]

    if col_location not in df.columns: df[col_location] = "Unknown Branch"

    dim_location = df[[col_location]].drop_duplicates().sort_values(col_location).reset_index(drop=True)
    dim_location = dim_location.rename(columns={col_location: "location_name"})
    dim_location.insert(0, "location_id", range(1, len(dim_location) + 1))


    if col_product not in df.columns: df[col_product] = "Unknown Product"

    dim_product = df[[col_product]].drop_duplicates().sort_values(col_product).reset_index(drop=True)
    dim_product = dim_product.rename(columns={col_product: "product_name"})
    dim_product.insert(0, "product_id", range(1, len(dim_product) + 1))


    mapped = df.copy()
    mapped['date_id'] = mapped[col_date].dt.strftime("%Y%m%d").astype(int)

    mapped = mapped.merge(dim_location, left_on=col_location, right_on="location_name", how="left")
    mapped = mapped.merge(dim_product, left_on=col_product, right_on="product_name", how="left")

    mapped['total_amount'] = mapped[col_qty] * mapped[col_price]

    if col_tx not in mapped.columns:
        mapped['transaction_id'] = [f"TX-{i:05d}" for i in range(1, len(mapped) + 1)]
        col_tx = 'transaction_id'

    fact_sales = mapped[[col_tx, "location_id", "product_id", "date_id", col_qty, col_price, "total_amount"]].copy()
    fact_sales = fact_sales.rename(columns={
        col_tx: "transaction_id",
        col_qty: "quantity",
        col_price: "unit_price"
    })

    print(f"[Transform] Locations={len(dim_location)}, Products={len(dim_product)}, Dates={len(dim_date)}, Sales Records={len(fact_sales)}")
    return dim_location, dim_product, dim_date, fact_sales

def load(dim_location, dim_product, dim_date, fact_sales):
    """Load: โหลดข้อมูลทั้งหมดลงใน SQLite"""
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("PRAGMA foreign_keys = ON;")

        conn.executescript("""
        DROP TABLE IF EXISTS fact_sales;
        DROP TABLE IF EXISTS dim_location;
        DROP TABLE IF EXISTS dim_product;
        DROP TABLE IF EXISTS dim_date;

        CREATE TABLE dim_location (
            location_id INTEGER PRIMARY KEY,
            location_name TEXT NOT NULL
        );

        CREATE TABLE dim_product (
            product_id INTEGER PRIMARY KEY,
            product_name TEXT NOT NULL
        );

        CREATE TABLE dim_date (
            date_id INTEGER PRIMARY KEY,
            full_date TEXT NOT NULL UNIQUE,
            day INTEGER NOT NULL,
            month INTEGER NOT NULL,
            year INTEGER NOT NULL
        );

        CREATE TABLE fact_sales (
            transaction_id TEXT PRIMARY KEY,
            location_id INTEGER NOT NULL REFERENCES dim_location(location_id),
            product_id INTEGER NOT NULL REFERENCES dim_product(product_id),
            date_id INTEGER NOT NULL REFERENCES dim_date(date_id),
            quantity INTEGER NOT NULL,
            unit_price REAL NOT NULL,
            total_amount REAL NOT NULL
        );
        """)

        dim_location.to_sql("dim_location", conn, if_exists="append", index=False)
        dim_product.to_sql("dim_product", conn, if_exists="append", index=False)
        dim_date.to_sql("dim_date", conn, if_exists="append", index=False)
        fact_sales.to_sql("fact_sales", conn, if_exists="append", index=False)

    print(f"[Load] Data successfully saved to {DB_PATH}")

if __name__ == "__main__":
    print("--- Starting ETL Pipeline ---")
    try:
        raw_data = extract()
        d_loc, d_prod, d_date, f_sales = transform(raw_data)
        load(d_loc, d_prod, d_date, f_sales)
        print("--- ETL Pipeline Completed Successfully! ---")
    except Exception as e:
        print(f"Error during execution: {e}")